scan_interval: 10
login_timeout: 5
cookie_ttl_seconds: 3600
max_device_failures: 5
device_check_interval: 15
invalid_check_every_n_cycles: 5
credentials:
  - username: admin
    password: admin
  - username: user
    password: pass

process:
  mode: debug
  interface: eno1 # or enx72b1b1c1c8da
  # public_ip: 192.168.0.3 # if known, otherwise it will be dynamically discovered
