{
 "title": "test",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "current", "label": "Select a metric", "query": { "query": "label_values(machine)" } },
   {
    "name": "denominator",
    "query": "5m, 15m, 30m, 1h, 3h, 6h, 12h, 24h, 2d, 7d, 30d, 90d\n"
   },
   {
    "name": "numerator",
    "query": "1m, 5m, 10m, 15m, 20m, 30m, 1h, 2h, 3h, 6h, 12h, 24h"
   },
   {
    "name": "multiplier",
    "query": "1,2,3,4,5,6,7,8,9,10,12,15,24,30,60"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(washer_1{machine=~\"$current\"}[1d])",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Pieces Per Minute x Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "increase(washer_1{machine=~\"$current\"}[30m]) / 30",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "throughput as a % of the average speed over the last hour",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(washer_1{machine=~\"$current\"}[1m]) / increase(washer_1{machine=~\"$current\"}[60m])) * 60 * 100",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Current Hour / Last 24 Hours",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(washer_1{machine=~\"$current\"}[1h]) / increase(washer_1{machine=~\"$current\"}[24h])) * 24",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Pieces Per Minute Histogram",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 11 },
   "targets": [
    {
     "expr": "increase(washer_1{machine=~\"$current\"}[1m])",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Pieces Processed",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(washer_1{machine=~\"$current\"}[$__range])",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Pieces Per Minute x Time",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 11 },
   "targets": [
    {
     "expr": "increase(washer_1{machine=~\"$current\"}[1m])",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Relative Productivity",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "(increase(washer_1{machine=~\"$current\"}[$numerator]) / increase(washer_1{machine=~\"$current\"}[$denominator])) * $multiplier",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Pieces Per Minute x Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "increase(washer_1{machine=~\"$current\"}[1m])",
     "legendFormat": "{{machine}}"
    }
   ]
  }
 ]
}